name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clojure tools-deps
      # uses: DeLaGuardo/setup-clojure@master
      uses: ./
      with:
        cli: 1.10.1.693
        
    - name: Execute clojure code on Linux and MacOS
      run: clojure -e "(+ 1 1)"
      shell: bash
