name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.4
      with:
        # Install just one or all simultaneously
        cli: 1.10.1.693 # Clojure CLI based on tools.deps
        lein: 2.9.1     # or use 'latest' to always provision latest version of leiningen
        boot: 2.8.3     # or use 'latest' to always provision latest version of boot
        
    - name: Execute clojure code on Linux and MacOS
      run: clojure -e "(+ 1 1)"
      shell: bash
    
    - name: do uberjar 
      run: clojure -A:prod uberjar windows
      shell: bash
